---

dist: trusty
  # - precise
  # - trusty
  # - xenial
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script: 
  - ansible-playbook -i inventory/inventory playbooks/guacamole_server_pb.yml --syntax-check
  - ansible-playbook -i inventory/inventory playbooks/guacamole_client_pb.yml --syntax-check
  - ansible-playbook -i inventory/inventory playbooks/guacamole_client_pb.yml
  - ansible-playbook -i inventory/inventory playbooks/guacamole_server_pb.yml
