---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install epel-release for CentOS
  yum: name=epel-release state=latest update_cache=yes
  when: ansible_distribution == "CentOS"
  tags: install

- name: Install dependencies for guacamole
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=latest
  with_items: '{{ PACKAGES }}'
  tags: install
