---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- tags: install
  block:
  - name: Add Oracle Java repository
    apt_repository: repo="ppa:webupd8team/java"
    when: ansible_distribution == "Ubuntu"

  - when: ansible_distribution == "CentOS"
    block:
    - name: Install epel-release for CentOS
      yum: name=epel-release state=latest update_cache=yes
    - name: Remove realvnc from CentOS atmoVM
      yum: name=realvnc-vnc-server state=absent

  - name: Install dependencies for guacamole
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=latest
    with_items: '{{ PACKAGES }}'

- name: Make '{{ GUACAMOLE_HOME_CLIENT }}' directory
  file: path='{{ GUACAMOLE_HOME_CLIENT }}' state=directory
  tags: configuration

- name: Add guacamole.properties to "{{ GUACAMOLE_HOME_CLIENT }}"
  template: src="guacamole.properties.j2" dest="{{ GUACAMOLE_HOME_CLIENT }}/guacamole.properties"
  tags: template

- tags: vnc
  block:
  - name: kill all running vncserver sessions
    shell: /bin/su {{ VNC_USER }} -c "/usr/bin/{{ VNC_COMMAND }} -kill :'{{ item }}'"
    with_items:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    failed_when: False
  - name: Configure VNC password
    shell: /bin/su {{ VNC_USER }} -c "/usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | {{ VNC_PASS_COMMAND }}"
  - name: start vncserver
    shell: /bin/su {{ VNC_USER }} -c {{ VNC_COMMAND }}

- name: restart guacd
  service: name=guacd state=restarted
  tags: restart
