---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Make '{{ GUACAMOLE_HOME_CLIENT }}' directory
  file: path='{{ GUACAMOLE_HOME_CLIENT }}' state=directory
  tags: configuration

- name: Add guacamole.properties to "{{ GUACAMOLE_HOME_CLIENT }}"
  template: src="guacamole.properties.j2" dest="{{ GUACAMOLE_HOME_CLIENT }}/guacamole.properties"
  tags: template

- tags: vnc
  block:
  - name: kill all running vncserver sessions
    shell: /bin/su {{ VNC_USER }} -c "/usr/bin/{{ VNC_COMMAND }} -kill :'{{ item }}'"
    with_items:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    failed_when: False
  - name: Disable encryption in realvnc
    lineinfile: 
      dest: /etc/vnc/config.custom
      state: present
      backrefs: yes
      regexp: "^SecurityTypes=RA2"
      line: "SecurityTypes=VncAuth"
  - name: start vncserver
    shell: /usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | /bin/su {{ VNC_USER }} -c {{ VNC_COMMAND }}

# task for changing VNC pass if for some reason the above task doesn't do it
# - name: Configure VNC password
#   shell: /bin/su {{ VNC_USER }} -c "/usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | {{ VNC_PASS_COMMAND }}"
