---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Add Oracle Java repository
  apt_repository: repo="ppa:webupd8team/java"
  when: ansible_distribution == "Ubuntu"

- name: Install epel-release for CentOS
  yum: name=epel-release state=latest update_cache=yes
  when: ansible_distribution == "CentOS"
  tags: install

#Only necessary for VMs I am testing on bc realvnc is installed
- name: Remove realvnc from CentOS atmoVM
  yum: name=realvnc-vnc-server state=absent
  when: ansible_distribution == "CentOS"
  tags: install

- name: Install dependencies for guacamole
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=latest
  with_items: '{{ PACKAGES }}'
  tags: install

- name: Make '{{ GUACAMOLE_HOME_CLIENT }}' directory
  file: path='{{ GUACAMOLE_HOME_CLIENT }}' state=directory
  tags: configuration

- name: Add guacamole.properties to "{{ GUACAMOLE_HOME_CLIENT }}"
  template: src="guacamole.properties.j2" dest="{{ GUACAMOLE_HOME_CLIENT }}/guacamole.properties"
  tags: template

- name: kill all running vncserver sessions
  shell: /bin/su {{ VNC_USER }} -c "/usr/bin/{{ VNC_COMMAND }} -kill :'{{ item }}'"
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  failed_when: False
  tags: vnc

- name: Configure VNC password
  shell: /bin/su {{ VNC_USER }} -c "/usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | {{ VNC_PASS_COMMAND }}"
  tags: vnc

- name: start vncserver
  shell: /bin/su {{ VNC_USER }} -c {{ VNC_COMMAND }}
  tags: vnc

- name: restart guacd
  service: name=guacd state=restarted
  tags: restart
