---

### Install dependencies

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install epel-release for CentOS
  yum: name=epel-release state=latest update_cache=yes
  when: ansible_distribution == "CentOS"
  tags: install

- name: Install dependencies for guacamole
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=latest
  with_items: '{{ PACKAGES }}'
  tags: install

### Install guacamole-server

- name: Download the guacamole-server source
  get_url: 
    url: "http://sourceforge.net/projects/guacamole/files/current/source/{{ GUACAMOLE_VERSION }}.tar.gz"
    dest: "/tmp/"
    timeout: 30
  tags: download

- name: Extract the guacamole-server source
  unarchive: src="/tmp/{{ GUACAMOLE_VERSION }}.tar.gz" copy=no dest="/tmp/"
  tags: extract

- name: Build guacamole-server from source (./configure)
  command: ./configure --with-init-dir=/etc/init.d chdir=/tmp/{{ GUACAMOLE_VERSION }}
  tags: build, install

- name: Build guacamole-server from source (make)
  command: make chdir=/tmp/{{ GUACAMOLE_VERSION }}
  tags: build, install

- name: Build guacamole-server from source (make install)
  command: make install chdir=/tmp/{{ GUACAMOLE_VERSION }}
  tags: build, install

- name: Build guacamole-server from source (ldconfig)
  command: ldconfig
  tags: build, install

- name: Download gaucamole.war
  get_url: 
    url: "http://sourceforge.net/projects/guacamole/files/current/binary/{{ GUACAMOLE_WAR }}.war"
    dest: "/var/lib/{{ TOMCAT_VERSION }}/webapps/guacamole.war"
    timeout: 30
    force: yes
  tags: download

- name: restart tomcat
  service: name={{ TOMCAT_VERSION }} state=restarted
  tags: restart

- name: restart guacd
  service: name=guacd state=restarted
  tags: restart

- name: delete {{ GUACAMOLE_VERSION }}.tar.gz
  file: path=/tmp/{{ GUACAMOLE_VERSION }}.tar.gz state=absent
  tags: clear-files

- name: delete {{ GUACAMOLE_VERSION }} directory
  file: path=/tmp/{{ GUACAMOLE_VERSION }} state=absent
  tags: clear-files

### Configure guacamole-server

- name: Make '{{ GUACAMOLE_HOME }}' directory
  file: path='{{ GUACAMOLE_HOME }}' state=directory
  tags: configuration

- name: Add guacamole.properties to "{{ GUACAMOLE_HOME }}"
  template: src="guacamole.properties.j2" dest="{{ GUACAMOLE_HOME }}/guacamole.properties"
  tags: template

- name: Add user-mapping.xml to "{{ GUACAMOLE_HOME }}"
  template: src="user-mapping.xml.j2" dest="{{ GUACAMOLE_HOME }}/user-mapping.xml"
  tags: template

- name: restart tomcat
  service: name={{ TOMCAT_VERSION }} state=restarted
  tags: restart

- name: restart guacd
  service: name=guacd state=restarted
  tags: restart
  