---

- name: Add new user
  shell: echo "SET @salt = UNHEX(SHA2(UUID(), 256)); INSERT INTO guacamole_user (username, password_salt, password_hash) VALUES ('{{ user_add }}', @salt, UNHEX(SHA2(CONCAT('{{ pass_add }}', HEX(@salt)), 256)));" | mysql -u root {{ database_name }}
  tags: user

- name: Add new connection
  shell: echo "INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('{{ connection_add.name }}', '{{ connection_add.protocol }}');" | mysql -u root {{ database_name }}

- name: Find the connection_id of the recently added connection
  shell: echo "select connection_id from guacamole_connection where connection_name = '{{ connection_add.name }}';" | mysql -u root salsa | grep -v connection_id
  register: con_id

- name: Add parameters to the new connection
  shell: echo "INSERT INTO guacamole_connection_parameter VALUES ({{ con_id.stdout }}, '{{ item.param }}', '{{ item.value }}');" | mysql -u root {{ database_name }}
  with_items: "{{ connection_add.param_list }}"

