---

PACKAGES:
  - cairo-devel
  - libjpeg-devel
  - libpng-devel
  - uuid-devel
  # Optionals:
  - freerdp-devel
  - pango-devel
  - libssh2-devel
  - libtelnet-devel
  - libvncserver-devel
  - pulseaudio-libs-devel
  - openssl-devel
  - libvorbis-devel
  - libwebp-devel
  - tomcat7
