---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Make '{{ GUACAMOLE_HOME }}' directory
  file: path='{{ GUACAMOLE_HOME }}' state=directory
  tags: configuration

- name: Add guacamole.properties to "{{GUACAMOLE_HOME}}"
  template: src="guacamole.properties.j2" dest="{{ GUACAMOLE_HOME }}/guacamole.properties"
  tags: template

- name: Add user-mapping.xml to "{{ GUACAMOLE_HOME }}"
  template: src="user-mapping.xml.j2" dest="{{ GUACAMOLE_HOME }}/user-mapping.xml"
  tags: template

- name: restart tomcat
  service: name={{ TOMCAT_VERSION }} state=restarted
  tags: restart

- name: restart guacd
  service: name=guacd state=restarted
  tags: restart