---

- name: Kill all running vncserver sessions
  shell: /bin/su {{ VNC_USER }} -c "/usr/bin/{{ VNC_COMMAND }} -kill :'{{ item }}'"
  with_items: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
  failed_when: False

- name: Disable encryption in realvnc
  lineinfile: 
    dest: /etc/vnc/config.custom
    state: present
    backrefs: yes
    regexp: "^SecurityTypes=RA2"
    line: "SecurityTypes=VncAuth"

- name: Start vncserver
  shell: /usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | /bin/su {{ VNC_USER }} -c {{ VNC_COMMAND }}

- name: Add the server's key to the client
  lineinfile: 
    dest: "/home/{{ atmo_user }}/.ssh/authorized_keys"
    line: '{{ server_key }}'
    state: present
  tags: key

# task for changing VNC pass if needed
# - name: Configure VNC password
#   shell: /bin/su {{ VNC_USER }} -c "/usr/bin/printf '%s\n%s\n' '{{ VNC_PASS }}' '{{ VNC_PASS }}' | {{ VNC_PASS_COMMAND }}"
